<?php
/**
 * Created by PhpStorm.
 * User: dsmrt
 * Date: 1/9/18
 * Time: 9:11 AM
 */

namespace flipbox\saml\sp;


use Craft;
use craft\base\Plugin;
use craft\console\Application as ConsoleApplication;
use craft\web\twig\variables\CraftVariable;
use flipbox\saml\sp\models\Settings;
use flipbox\saml\sp\services\AuthnRequest;
use flipbox\saml\sp\services\EntityDescriptors;
use flipbox\saml\sp\services\HttpPost;
use flipbox\saml\sp\services\HttpRedirect;
use flipbox\saml\sp\services\Login;
use flipbox\saml\sp\services\Metadata;
use flipbox\saml\sp\services\Response;
use flipbox\saml\sp\services\Provider;
use flipbox\saml\sp\services\ProviderIdentity;
use yii\base\Event;

class Saml extends Plugin
{

//    public $controllerNamespace = __NAMESPACE__ . '\cli';
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub


         // Switch target to console controllers
        if (Craft::$app instanceof ConsoleApplication) {
            $this->controllerNamespace = __NAMESPACE__ . '\cli';
            $this->controllerMap = [
                'metadata' => \flipbox\saml\sp\cli\Metadata::class,
            ];
        }

        // Template variables
        Event::on(
            CraftVariable::class,
            CraftVariable::EVENT_INIT,
            function (Event $event) {
                /** @var CraftVariable $variable */
                $variable = $event->sender;
                $variable->set('patron', PatronVariable::class);
            }
        );
    }

    /**
     * @return Settings
     */
    public function getSettings()
    {
        return parent::getSettings(); // TODO: Change the autogenerated stub
    }

    public function createSettingsModel()
    {
        return new Settings();
    }



    /**
     * Components
     */

    /**
     * @return Metadata
     */
    public function getMetadata(){
        return $this->get('metadata');
    }

    /**
     * @return AuthnRequest
     */
    public function getAuthnRequest()
    {
        return $this->get('authnRequest');
    }

    /**
     * @return Response
     */
    public function getResponse(){
        return $this->get('response');
    }

    /**
     * @return Login
     */
    public function getLogin()
    {
        return $this->get('login');
    }

    /**
     * @return HttpPost
     */
    public function getHttpPost()
    {
        return $this->get('httpPost');
    }

    /**
     * @return HttpRedirect
     */
    public function getHttpRedirect()
    {
        return $this->get('httpRedirect');
    }

    /**
     * @return EntityDescriptors
     */
    public function getEntityDescriptors()
    {
        return $this->get('entityDescriptors');
    }

    /**
     * @returns Provider
     */
    public function getProvider(){
        return $this->get('provider');
    }

    /**
     * @returns ProviderIdentity
     */
    public function getProviderIdentity(){
        return $this->get('providerIdentity');
    }
}